/**
 * Supabase Database Types
 *
 * AUTO-GENERATED by Supabase CLI
 * To regenerate: npm run db:types
 *
 * DO NOT EDIT MANUALLY
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          display_name: string | null;
          bio: string | null;
          avatar_url: string | null;
          preferred_dialect: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi';
          learning_style: 'visual' | 'auditory' | 'kinesthetic' | 'reading_writing' | 'mixed';
          native_language: string;
          target_languages: string[];
          email_notifications: boolean;
          push_notifications: boolean;
          daily_goal_minutes: number;
          preferred_study_time: string | null;
          timezone: string;
          country_code: string | null;
          education_level: string | null;
          created_at: string;
          updated_at: string;
          last_active_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          preferred_dialect?: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi';
          learning_style?: 'visual' | 'auditory' | 'kinesthetic' | 'reading_writing' | 'mixed';
          native_language?: string;
          target_languages?: string[];
          email_notifications?: boolean;
          push_notifications?: boolean;
          daily_goal_minutes?: number;
          preferred_study_time?: string | null;
          timezone?: string;
          country_code?: string | null;
          education_level?: string | null;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          preferred_dialect?: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi';
          learning_style?: 'visual' | 'auditory' | 'kinesthetic' | 'reading_writing' | 'mixed';
          native_language?: string;
          target_languages?: string[];
          email_notifications?: boolean;
          push_notifications?: boolean;
          daily_goal_minutes?: number;
          preferred_study_time?: string | null;
          timezone?: string;
          country_code?: string | null;
          education_level?: string | null;
          updated_at?: string;
          last_active_at?: string;
        };
      };
      knowledge_components: {
        Row: {
          id: string;
          code: string;
          name_en: string;
          name_ar: string;
          description_en: string | null;
          description_ar: string | null;
          subject: string;
          topic: string;
          subtopic: string | null;
          prerequisites: string[];
          related_kcs: string[];
          difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
          learning_objectives: string[];
          common_misconceptions: string[];
          estimated_time_minutes: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name_en: string;
          name_ar: string;
          description_en?: string | null;
          description_ar?: string | null;
          subject: string;
          topic: string;
          subtopic?: string | null;
          prerequisites?: string[];
          related_kcs?: string[];
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
          learning_objectives?: string[];
          common_misconceptions?: string[];
          estimated_time_minutes?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          name_en?: string;
          name_ar?: string;
          description_en?: string | null;
          description_ar?: string | null;
          subject?: string;
          topic?: string;
          subtopic?: string | null;
          prerequisites?: string[];
          related_kcs?: string[];
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
          learning_objectives?: string[];
          common_misconceptions?: string[];
          estimated_time_minutes?: number | null;
          updated_at?: string;
        };
      };
      student_mastery: {
        Row: {
          id: string;
          user_id: string;
          kc_id: string;
          stability: number;
          difficulty: number;
          retrievability: number;
          p_know: number;
          p_learn: number;
          p_slip: number;
          p_guess: number;
          last_reviewed_at: string | null;
          next_review_at: string | null;
          review_count: number;
          total_correct: number;
          total_incorrect: number;
          total_time_spent_seconds: number;
          average_response_time_seconds: number | null;
          mastery_level: number;
          is_mastered: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kc_id: string;
          stability?: number;
          difficulty?: number;
          retrievability?: number;
          p_know?: number;
          p_learn?: number;
          p_slip?: number;
          p_guess?: number;
          last_reviewed_at?: string | null;
          next_review_at?: string | null;
          review_count?: number;
          total_correct?: number;
          total_incorrect?: number;
          total_time_spent_seconds?: number;
          average_response_time_seconds?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          stability?: number;
          difficulty?: number;
          retrievability?: number;
          p_know?: number;
          p_learn?: number;
          p_slip?: number;
          p_guess?: number;
          last_reviewed_at?: string | null;
          next_review_at?: string | null;
          review_count?: number;
          total_correct?: number;
          total_incorrect?: number;
          total_time_spent_seconds?: number;
          average_response_time_seconds?: number | null;
          updated_at?: string;
        };
      };
      lessons: {
        Row: {
          id: string;
          title_en: string;
          title_ar: string;
          slug: string;
          description_en: string | null;
          description_ar: string | null;
          content: Json;
          subject: string;
          topic: string;
          difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
          kc_ids: string[];
          prerequisite_lesson_ids: string[];
          estimated_duration_minutes: number;
          is_published: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_ar: string;
          slug: string;
          description_en?: string | null;
          description_ar?: string | null;
          content: Json;
          subject: string;
          topic: string;
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
          kc_ids?: string[];
          prerequisite_lesson_ids?: string[];
          estimated_duration_minutes?: number;
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title_en?: string;
          title_ar?: string;
          slug?: string;
          description_en?: string | null;
          description_ar?: string | null;
          content?: Json;
          subject?: string;
          topic?: string;
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
          kc_ids?: string[];
          prerequisite_lesson_ids?: string[];
          estimated_duration_minutes?: number;
          is_published?: boolean;
          published_at?: string | null;
          updated_at?: string;
        };
      };
      student_progress: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          status: 'not_started' | 'in_progress' | 'completed' | 'mastered';
          progress_percent: number;
          time_spent_seconds: number;
          last_position: Json | null;
          exercises_completed: number;
          exercises_correct: number;
          quiz_score: number | null;
          started_at: string | null;
          completed_at: string | null;
          last_accessed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_id: string;
          status?: 'not_started' | 'in_progress' | 'completed' | 'mastered';
          progress_percent?: number;
          time_spent_seconds?: number;
          last_position?: Json | null;
          exercises_completed?: number;
          exercises_correct?: number;
          quiz_score?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          last_accessed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'not_started' | 'in_progress' | 'completed' | 'mastered';
          progress_percent?: number;
          time_spent_seconds?: number;
          last_position?: Json | null;
          exercises_completed?: number;
          exercises_correct?: number;
          quiz_score?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          last_accessed_at?: string | null;
          updated_at?: string;
        };
      };
      agent_sessions: {
        Row: {
          id: string;
          user_id: string;
          agent_type: string;
          agent_version: string;
          input: string;
          output: Json | null;
          context: Json | null;
          model_used: string | null;
          duration_ms: number | null;
          tokens_input: number | null;
          tokens_output: number | null;
          cost_usd: number | null;
          self_reflection_score: number | null;
          student_feedback: number | null;
          was_helpful: boolean | null;
          dialect_used: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi' | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          agent_type: string;
          agent_version?: string;
          input: string;
          output?: Json | null;
          context?: Json | null;
          model_used?: string | null;
          duration_ms?: number | null;
          tokens_input?: number | null;
          tokens_output?: number | null;
          cost_usd?: number | null;
          self_reflection_score?: number | null;
          student_feedback?: number | null;
          was_helpful?: boolean | null;
          dialect_used?: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi' | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          agent_type?: string;
          agent_version?: string;
          input?: string;
          output?: Json | null;
          context?: Json | null;
          model_used?: string | null;
          duration_ms?: number | null;
          tokens_input?: number | null;
          tokens_output?: number | null;
          cost_usd?: number | null;
          self_reflection_score?: number | null;
          student_feedback?: number | null;
          was_helpful?: boolean | null;
          dialect_used?: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi' | null;
          error_message?: string | null;
        };
      };
      flashcards: {
        Row: {
          id: string;
          user_id: string;
          kc_id: string;
          front_text: string;
          back_text: string;
          hints: string[];
          due_date: string;
          stability: number;
          difficulty: number;
          elapsed_days: number;
          scheduled_days: number;
          reps: number;
          lapses: number;
          state: string;
          last_reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kc_id: string;
          front_text: string;
          back_text: string;
          hints?: string[];
          due_date?: string;
          stability?: number;
          difficulty?: number;
          elapsed_days?: number;
          scheduled_days?: number;
          reps?: number;
          lapses?: number;
          state?: string;
          last_reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          front_text?: string;
          back_text?: string;
          hints?: string[];
          due_date?: string;
          stability?: number;
          difficulty?: number;
          elapsed_days?: number;
          scheduled_days?: number;
          reps?: number;
          lapses?: number;
          state?: string;
          last_reviewed_at?: string | null;
          updated_at?: string;
        };
      };
      review_history: {
        Row: {
          id: string;
          user_id: string;
          flashcard_id: string;
          rating: number;
          time_taken_seconds: number | null;
          state_before: string;
          stability_before: number | null;
          difficulty_before: number | null;
          state_after: string;
          stability_after: number | null;
          difficulty_after: number | null;
          reviewed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          flashcard_id: string;
          rating: number;
          time_taken_seconds?: number | null;
          state_before: string;
          stability_before?: number | null;
          difficulty_before?: number | null;
          state_after: string;
          stability_after?: number | null;
          difficulty_after?: number | null;
          reviewed_at?: string;
        };
        Update: {
          rating?: number;
          time_taken_seconds?: number | null;
          state_before?: string;
          stability_before?: number | null;
          difficulty_before?: number | null;
          state_after?: string;
          stability_after?: number | null;
          difficulty_after?: number | null;
        };
      };
      achievements: {
        Row: {
          id: string;
          code: string;
          name_en: string;
          name_ar: string;
          description_en: string | null;
          description_ar: string | null;
          icon_url: string | null;
          color: string | null;
          criteria: Json;
          points: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name_en: string;
          name_ar: string;
          description_en?: string | null;
          description_ar?: string | null;
          icon_url?: string | null;
          color?: string | null;
          criteria: Json;
          points?: number;
          created_at?: string;
        };
        Update: {
          code?: string;
          name_en?: string;
          name_ar?: string;
          description_en?: string | null;
          description_ar?: string | null;
          icon_url?: string | null;
          color?: string | null;
          criteria?: Json;
          points?: number;
        };
      };
      student_achievements: {
        Row: {
          id: string;
          user_id: string;
          achievement_id: string;
          unlocked_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          achievement_id: string;
          unlocked_at?: string;
        };
        Update: {};
      };
      study_sessions: {
        Row: {
          id: string;
          user_id: string;
          started_at: string;
          ended_at: string | null;
          duration_seconds: number | null;
          lesson_ids: string[] | null;
          kc_ids: string[] | null;
          total_exercises: number;
          correct_exercises: number;
          flashcards_reviewed: number;
          focus_score: number | null;
          breaks_taken: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          started_at?: string;
          ended_at?: string | null;
          duration_seconds?: number | null;
          lesson_ids?: string[] | null;
          kc_ids?: string[] | null;
          total_exercises?: number;
          correct_exercises?: number;
          flashcards_reviewed?: number;
          focus_score?: number | null;
          breaks_taken?: number;
          created_at?: string;
        };
        Update: {
          ended_at?: string | null;
          duration_seconds?: number | null;
          lesson_ids?: string[] | null;
          kc_ids?: string[] | null;
          total_exercises?: number;
          correct_exercises?: number;
          flashcards_reviewed?: number;
          focus_score?: number | null;
          breaks_taken?: number;
        };
      };
    };
    Views: {};
    Functions: {
      get_student_overall_mastery: {
        Args: { student_id: string };
        Returns: number;
      };
      get_study_streak: {
        Args: { student_id: string };
        Returns: number;
      };
    };
    Enums: {
      arabic_dialect: 'MSA' | 'Egyptian' | 'Gulf' | 'Levantine' | 'Maghrebi';
      learning_style: 'visual' | 'auditory' | 'kinesthetic' | 'reading_writing' | 'mixed';
      difficulty_level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
      progress_status: 'not_started' | 'in_progress' | 'completed' | 'mastered';
      agent_type: 'visualizer' | 'narrator' | 'problem_decomposer' | 'simulator' | 'socratic' | 'spaced_repetition' | 'adaptive_assessor' | 'cognitive_mirror' | 'memory_architect' | 'context_weaver' | 'research_companion' | 'language_coach' | 'engagement_monitor' | 'wellbeing' | 'maestro';
    };
  };
}
